# Site settings
title: Viopop - Software Design and Development
email: hi@viopop.com
description: "Software Design and Development"
url: http://viopop.com
twitter_username: viopop

# Build settings
encoding: utf-8
timezone: US/Pacific
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "README.md"]
markdown: kramdown
kramdown:
  entity_output: :symbolic
relative_permalinks: true
assets:
  dirname: public-assets
  baseurl: /public-assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
  js_compressor: uglifier
  css_compressor: sass
  cachebust: hard


# Post permalink style
permalink: /projects/:title/

# Page defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
